#!/bin/bash
moje_url_p1="rtmp://stream85.polskieradio.pl/omniaaxe/k"
moje_url_p2=".stream"

regular_station_url="http://stream.polskieradio.pl/program"

stream_number[0]=34
stream_name[0]="minimax"
stream_number[1]=41
stream_name[1]="classic_rock"
stream_number[2]=42
stream_name[2]="prog_rock"
stream_number[3]=26
stream_name[3]="opener"
stream_number[4]=20
stream_name[4]="mann_niedzwiedz"
stream_number[5]=50
stream_name[5]="city_groove"
stream_number[6]=45
stream_name[6]="led_zeppelin"
stream_number[7]=44
stream_name[7]="prl"
stream_number[8]=35
stream_name[8]="offensywa"
stream_number[9]=29
stream_name[9]="indie"
stream_number[10]=28
stream_name[10]="modern_rock"
stream_number[11]=23
stream_name[11]="jazz"
stream_number[12]=21
stream_name[12]="polskie"
stream_number[13]=27
stream_name[13]="rnb"
stream_number[14]=30
stream_name[14]="reggae"
stream_number[15]=43
stream_name[15]="blues_brothers"
stream_number[16]=16
stream_name[16]="koncerty"
stream_number[17]=18
stream_name[17]="rozrywka"
stream_number[18]=47
stream_name[18]="pop"

station_name[0]="jedynka"
station_name[1]="dwojka"
station_name[2]="trojka"
station_name[3]="euro"

stream_type="0";

usage()
{
	echo "Usage: $0 [stream_to_play]"
	echo
	echo "Moje.polskieradio.pl streams are:"
	for i in $(seq 0 $((${#stream_name[*]}-1))); do
		echo "  o ${stream_name[$i]}"
	done;
	echo
	echo "Regular stations are:"
	for i in $(seq 0 $((${#station_name[*]}-1))); do
		echo "  o ${station_name[$i]}"
	done;


}

if [ "$1" == "" ] || [ $# != 1 ]; then
	usage
	exit
fi

for i in $(seq 0 $((${#stream_name[*]}-1))); do
	if [ "${stream_name[$i]}" == "$1" ]; then
		STREAM_URL="$moje_url_p1${stream_number[$i]}$moje_url_p2";
		streamtype="1";
		break;
	fi;
done;

if [ "$STREAM_URL" == "" ]; then
	for i in $(seq 0 $((${#station_name[*]}-1))); do
		if [ "${station_name[$i]}" == "$1" ]; then
			STREAM_URL="$regular_station_url$((i + 1))";
			streamtype="2";
		break;
	fi;
	done;
fi;

if [ "$STREAM_URL" == "" ]; then
	usage
	exit
fi;

if [ "$streamtype" == "1" ]; then
	echo "Playing stream $1"
	mkfifo /tmp/radio
	rtmpdump --timeout 7 --rtmp "$STREAM_URL" --live  -o /tmp/radio 2> /dev/null &
	sleep 1;
	mplayer /tmp/radio -novideo
	killall rtmpdump
	rm /tmp/radio
fi;
if [ "$streamtype" == "2" ]; then
	echo "Playing stream $1"
	mplayer -novideo -cache 128 -cache-min 70 "$STREAM_URL"
fi;

