#!/bin/bash 
URL1=http://stream.polskieradio.pl/program4
URL2=mms://stream.polskieradio.pl/program4

while true; do
	mplayer -cache 128 -cache-min 70 "$URL1"
	sleep 1
	mplayer -cache 128 -cache-min 70 "$URL2"
	sleep 1
done
